void main() {
  print('Create Square Shape');
  print('****************');
  print('*              *');
  print('*              *');
  print('*              *');
  print('*              *');
  print('****************');
  print('####################################');
  print('####################################');
  print('create rectangle chape');
  print('**************************');
  print('*                        *');
  print('*                        *');
  print('*                        *');
  print('**************************');
  print('####################################');
  print('####################################');
  print('create triangle chape');
  print('          *           ');
  print('         * *          ');
  print('        *   *         ');
  print('      *       *       ');
  print('    *************    ');
  print('####################################');
  print('####################################');
  print('create pentagoneshape');
  print('          *           ');
  print('     *          *     ');
  print(' *                  * ');
  print('  *                *  ');
  print('    *             *   ');
  print('      ***********     ');
  print('####################################');
  print('####################################');
  print("Create Circle shape");
  print("        ****             ");
  print("      *      *           ");
  print("     *         *   ");
  print("    *           * ");
  print("    *           *");
  print("     *          *   ");
  print("      *        *   ");
  print("        ******   ");
  print('####################################');
  print('####################################');
  print("Create pyramid shape");
  print('          *          ');
  print('         ***         ');
  print('        *****        ');
  print('      **********     ');
  print('    ***************  ');
}
